version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: inventaris-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${DB_NAME:-inventaris_bkn}
      MYSQL_USER: ${DB_USER:-inventaris_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - inventaris-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventaris-backend
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-inventaris_bkn}
      DB_USER: ${DB_USER:-inventaris_user}
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-key-change-in-production}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      - mysql
    networks:
      - inventaris-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: inventaris-frontend
    environment:
      VITE_API_URL: http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventaris-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  inventaris-network:
    driver: bridge